---
title: "Formal proposal document"
subtitle: "Eureka, I found a hike!"
author: "Ankush Garg"
date: "4/9/2018"
output: 
  html_document:
    toc: true
    number_sections: false
    theme: lumen
    highlight: espresso
---

## Summary

The goal of this project is to allow Alltrails users to receive 5 new recommendations for a hike they've enjoyed. "Eureka, I found a hike", is a 3rd party application that takes in *a hike and a location in California as inputs*, and *returns 5 hikes that the user is likely to enjoy* based upon number of criteria such as proximity, distance, elevation, etc. The application enables avid, as well as new hikers, to promote healthy living by reducing the time it takes between searching for a hike to getting out on the trail. Hikers can leverage technology to spend more time in nature. 

## Background

Alltrails is a crowdsourced website that helps millions of people explore the outdoors by providing the largest collection of photos, trailmaps and trail reviews. Though they have a large collection of hikes and reviews, choose the next hike can be challenging. Picking the perfect hike often requires careful considerations in terms of location, difficulty, and safety, even for avid hikers. Hikers end up consulting friends, TripAdvisors or other public forums for hiking recommendations. This can turn into a drawn out process. A recommendation system linking the Alltrails website for hikes can alleviate this painstaking research so that users spend more time outside in the nature, rather than on their computers. First time hikers in California can reap the rewards of hiking by starting out with easier hikes that are highly rated as well as carefully curated. 

## Project plan and timeline

Project plan is split into development stage and sustain modes

### Development mode - 11 weeks

#### 1. Data collection - 3 weeks
Eureka data science team to consult Alltrails data management team for hike related data. Data scientists will procure, wrangle and store data for model development. 

#### 2. Model development - 3 weeks
Eureka data science team will assess the data on hiking trails they have procured, build recommendation engines, train and evaluate model effectiveness. Top models that pass preliminary tests for hike similarity are to be implemented.

#### 3. EurekaIfoundahike website - 2 weeks
Eureka Front end engineers will build in house user interface where Alltrails users can access recommended hikes. 

#### 4. Project deployment and implementation - 3 weeks
Eureka data science team and data engineering team to implement the application in production. Training documents are prepared and the Eureka support team is on-boarded. 

### Sustain mode - 3 years

#### 1. A/B testing - every 2 weeks for the first month
Since the project is dependent on recommendations to be satisfactory for end users, multiple recommendation engines are to be tested in production via A/B testing. The output of the A/B testing includes metrics such as Click through rate, average time spent on each hike, likes and dislikes of hike recommendations. Depending on the A/B testing feedback, the final recommendation engine will become more successfull. 

#### 2. Model maintainence - every 6 months  
Data scientists to evaluate model performance on a 6 month cadence post-implementation. If the model performance falls under 40 % user satisfaction before 6 month period is over, data science team to procure additional data, and perform the required maintainence. 

## Success criteria 

The project will be considered a success when 65% of the end users find their first recommendation to be satisfactory and 50% of the users find their first 3 recommendations to be satisfactory. 

An active base of 100 users.  

Upon querying a hike, getting results in 5 seconds. 

## Key Stakeholders

End users - California residents who are looking for a hike

Alltrails users - Provided hike details, ratings and reviews 

Alltrails data management team

Product manager

Data science team 

Development team 

QA team - MechanicalTurks (in the case where the recommendation engine needs more human intervention)

## Risks

Tailoring hikes to specific user base is dependent on how many end users report out on their recommendations, whether successfull or unsuccessful. 

Competing services that hikers are already affiliated with can be challenging in getting more users. 

Application doesn't offer weather influenced services, and can produce interesting results based on upredictable weather. Which can in turn reflect poorly on the app.  

## Risk mitigation

In the event that users don't report out on recommendations, data science team to leverage platforms such as MechanialTurks for human intervention for recommendation feedback. 

Linking the local weather report to the page can notify the users to check local weather before hiking
